<a href="https://colab.research.google.com/github/tsnow2010/DATA601/blob/main/DATA601_Notes/DATA601_Week6_Notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# DATA601 Week 6 Notes

In [ ]:
import re

# findall('',txt) may have issues finding all occurrences if any of them overlap with each other.


txt = 'DATA601: Introduction to Data Science'
x= re.split('\W',txt)
print(list(x))

None


<>:7: SyntaxWarning: invalid escape sequence '\W'
<>:7: SyntaxWarning: invalid escape sequence '\W'
/var/folders/yx/32mlh_nx5ns6v1zmf7rs6l8h0000gn/T/ipykernel_1678/2986904611.py:7: SyntaxWarning: invalid escape sequence '\W'
  x= re.split('\W',txt)


# Regex syntax for function: re.findall('char',txt)

In [ ]:
# Note that
#   * all comparisons are done on EVERY character in the input and counts blanks if your args would include them!
#   * if conditions apply multiple times in a segment, it will could all occurrences
# CHECK OUT regexr.com for help quick testing of your regex syntax!

# a+ -> at least (1) 'a'
# ae+ -> a AND at least (1) 'e'
# e? -> (0) OR (1) 'e', will count spaces and appear as ''
# e* -> (0) or more 'e'
# .at -> match any (1) character ending in 'at', if more than (1) before 'at', it will be truncated.
# \w -> any alphanumeric char including underscore
# \W -> any character NOT IN a match for '\w'
# \d -> any digit // equivalent to '[0-9]'
# \s -> any white space characteres (spaces, tabs, line breaks)
# ^rat -> starts with 'rat' // THIS DOES NOT COMPARE every char in string, only the beginning of entire string, and returns (1) element
# $rat -> ends with 'rat' // like above, THIS DOES NOT COMPARE every char in string, only the end of entire string and returns (1) element

# Look ahead operators:
# * Requires a combination of a properly oriented '.' and '?'

# ((?<=[tT]he).) ->  'positive look behind', returns any character that is preceded by "the" or 'The'
#.    * if given 'The Then they them thor', [' ','n','y','m'] would be returned
# (.(?=at)) -> positive look ahead //
# ((?<![tT]he).) -> negative look behind // inverse of positive look behind
# (.(?!at)) -> negative look ahead // inverse of positive look ahead


# Quantifiers
# e{min,max} -> find matches with at least (min) e and no more than (max) e

# Character Set
# [br]at -> match with b or r ending in 'at'. // Think of it as (b OR r + .at)

# Ranges in character sets.
# [a-zA-z]at -> match with lowercase letter or uppercase letter ending in 'at'.   // note that the '-' includes char to left and right as 1

# OR operator (|)
# "The|the" -> match 'The' or 'the'

# Parentheses: limits the scope of any operator, helps with hierarchy
# NOTE: if you use parentheses, the entire argument must be encapsulated by parentheses, otherwise it will not work.
#    * For instance, with "(T|t)he", the 'he' is ignored.  You must put in '((T|t)he)' to work properly.
#    * If "the" or "The" is passed in this case, you would get [('the','t'),('The','T')]
#        The parentheses act like another OR statement!
#.   * Really, the () act like "tuple makers"


In [ ]:
# Practical Examples:

# Look for numbers resembling DODIDs

# Look for names in format, 'LN, FN, MI.'



# NUMPY

In [ ]:
import numpy as np
import math

# all elements in an array MUST BE of same data type
# use np.(str|bool|int|float|complex)_(ndarray) to convert all elements to the requested data type!

array1 = np.array([1,2,3])
array1


array([1, 2, 3])

In [ ]:
type(array1)

numpy.ndarray

In [ ]:
array2 = np.array([1,0,1,0])
# Turn to bool

In [ ]:
# Creating 3x2 array

array4 = np.array([[1,2],[3,4],[5,6]])
array4

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
array4.shape # Same as pandas

(3, 2)

In [ ]:
array4.size # how many elements?

6

In [ ]:
array4[2][1] # should return '6', notice that this is indexing rowsxcol like python normally indexes

6

In [ ]:
array4[2,1] # this format is the same as well

6

In [ ]:
array4[:,0] # gives first column

array([1, 3, 5])

In [ ]:
array4[0,:] # gives first row

array([1, 2])

In [ ]:
array4[:][0] # WATCH OUT, this is odd but is equivalent to the above statement.  Avoid the [][] notation, it's confusing.

array([1, 2])

In [ ]:
# .flatten() concatenates row1 + row2 + row3 // 'row major form' == 'C'
array4.flatten() #Optional param is 'F' or 'C' // 'C' is default

array([1, 2, 3, 4, 5, 6])

In [ ]:
# .flatten() with 'column major form' or 'Fortran-style'
array4.flatten('F')

array([1, 3, 5, 2, 4, 6])

In [ ]:
# .reshape() make 2x3 matrix, pulls element by element, row major // arrays are immutable!
array4.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# .reshape() make 2x3 matrix, pulls element by element, column major
array4.reshape((2,3),order='F')

array([[1, 5, 4],
       [3, 2, 6]])

In [ ]:
# .reshape() with negative numbers asks python to decide the number of rows/columns given set row/column
# symmetry MUST be possible or error will be thrown

array4.reshape(-1,3) # should give 2x3 matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
array5 = np.arange(10) # acts like range(0) but makes an ndarray
array5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
array5.size # acts like len()

10

In [ ]:
array6 = np.arange(0,10,.5)
array6

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [ ]:
# .linspace() is similar to .arange() but it asks a range and how many elements you want, versus an increment.
array7 = np.linspace(0,4,20)
print(array7)
array7.shape

[0.         0.21052632 0.42105263 0.63157895 0.84210526 1.05263158
 1.26315789 1.47368421 1.68421053 1.89473684 2.10526316 2.31578947
 2.52631579 2.73684211 2.94736842 3.15789474 3.36842105 3.57894737
 3.78947368 4.        ]


(20,)

In [ ]:
array7.reshape(20,1)
array7.shape

(20,)

In [ ]:
array8 = np.array([[1],[2]]) # should be .shape should return (2,)
array8.shape # But it doesn't.... interesting.

(2, 1)

In [ ]:
# Useful methods:
#   * Use axis=0/1 param to isolate columns and rows.


#.ones() # makes an array of 1's
#.zeros() # makes an array of 0's
#.identity() provides identity matrix of given dimension

#.min()  #returns min in matrix // 'axis' param specifies the row
#.max()  #returns max in matrix
#.mean()
#.sum()
#.prod() # takes product of all elements
#.transpose() # rows become columns and vice versa
#    <ndarray>.T AND <ndarray>.swapaxes(0,1) -> will do the same thing

#.argmin() # returns location of min
#.argmax() # returns location of max

#np.copy(<ndarray>) # returns deep copy of array.
#.copy() # returns deep copy of array

In [ ]:
array4

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
array4.argmax() # how is this the location?

5

In [ ]:
# np has a subpackage of random
array10 = np.random.randint(1,10,12).reshape((4,3))
print(array10)

[[8 3 2]
 [8 9 5]
 [9 3 7]
 [2 6 2]]


In [ ]:
# This calculates the means in each column.
array10.mean(axis=0)

array([6.75, 5.25, 4.  ])

In [ ]:
# This calculates the means in each row.
array10.mean(axis=1)

array([4.33333333, 7.33333333, 6.33333333, 3.33333333])

# Matrix Creation Functions

In [ ]:
# Scalar Ops

# Addition
array10 = np.ones((3,3))
print(array10)
array10 +=5
print(array10)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]]


In [ ]:
# Power Ops

print(array10**2)

[[36. 36. 36.]
 [36. 36. 36.]
 [36. 36. 36.]]


In [ ]:
array11 = np.arange(1,7,1).reshape((3,2))
array11

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
array12 = np.arange(1,7,1).reshape((2,3))
array12

array([[1, 2, 3],
       [4, 5, 6]])

# Linear Algebra Functions

In [ ]:
# Multiply elements
print(array11*array11) # multiplies corresponding elements in arrays
print('---')
# print(array11*array12) # throws error, must have same dimensions

[[ 1  4]
 [ 9 16]
 [25 36]]
---
[[ 9 12 15]
 [19 26 33]
 [29 40 51]]


In [ ]:
np.log10(array11) # Applies function to each individual element

array([[0.        , 0.30103   ],
       [0.47712125, 0.60205999],
       [0.69897   , 0.77815125]])

In [ ]:
# Dot product
print(np.dot(array11,array12))
# another way...
print('---')
print(np.matmul(array11,array12))
# yet another...
print('---')
print(array11 @ array12)


[[ 9 12 15]
 [19 26 33]
 [29 40 51]]
---
[[ 9 12 15]
 [19 26 33]
 [29 40 51]]
---
[[ 9 12 15]
 [19 26 33]
 [29 40 51]]


In [ ]:
# Cross product
print(np.cross(array11,array11))

[0 0 0]


In [ ]:
# Eigenvalues
print(np.linalg.eig(array11))

LinAlgError: Last 2 dimensions of the array must be square

In [ ]:
# Inverse function
array13 = np.arange(1,10,1).reshape((3,3))
print(np.linalg.inv(array13))
print('---')
print(np.linalg.inv(array13) @ array13) # should be identity! (or not, review this concept)

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]
---
[[10. 12. 14.]
 [-4. -8. -4.]
 [-2.  0.  2.]]


In [ ]:
# Find determinant of array

print(np.linalg.det(array13))

-9.51619735392994e-16


# numpy.where() function

In [ ]:
# Returns locations of where elements are greater than 1, but less than 8.  Notice, it gives the x-values in one array and y-values in another.
np.where((array13>1) & (array13<8))

(array([0, 0, 1, 1, 1, 2]), array([1, 2, 0, 1, 2, 0]))

In [ ]:
# Replaces elements in an array.
new_array13 = np.where(array13==2,100,array13)
new_array13

array([[  1, 100,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [ ]:
# Does replacement, similar to above, and then makes rest of elements another value (or 0 in this case)
print(array13)
new_array13 = np.where(array13==1,2,0)
new_array13

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[2, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
# Vectorizing Functions // Not good for performance, it is mainly for convenience.

def funct1(val):
    if val < 0:
        return val+1
# funct1(array13) throws error, need to vectorize

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
# Doesn't work... why?
new_funct1 = np.vectorize(funct1)
print(new_funct1(array13))

[[None None None]
 [None None None]
 [None None None]]


# Saving output (proprietary Numpy formats)

In [ ]:
#np.save('test.npy', array_to_pass)
#np.savez('test', array_to_pass1, array_to_pass2)
# saved_files = np.load('test.npy').   /// this now has all files associated with test.npy
#saved_files.files. #gives names of files
   # May return [a1,a2]
#saved_array1 = saved_files['a1']
   # now, array in a1 is saved to saved_array1
#saved_files.close() // don't forget this!


# Lambda Functions

In [ ]:
!pip install pipe
from pipe import where,select

# Simple lambda function
funct1 = lambda input: print(input)

funct1('hello, test')

hello, test


In [ ]:
# You can use pipe to make a list-comprehension-type (mapping,filtering) expression

array = ['hi','hello','goodbye']

list(array| where(lambda x: x.upper()) | select(lambda x: len(x) >2))



[False, True, True]

In [ ]:
# Define a funct that returns a lambda function.
# Calculates number of repetitions based on your repetitions per set.

def num_reps(sets):
    return lambda reps: sets * reps

num_reps_8 = num_reps(4)
num_reps_8(8)

32